- name: install gonme3 with custom configuration for a dev machine
  hosts: all 
  roles:
    - role: baseline
    - role: java.version-8
    - role: code.tooling
    - role: gantsign.intellij
    
  vars:

   system_user: danfoulkes
   system_password: "$6$AXe355Juu21$zLqAAHyhL41xQhGCa4XRHDUPhl5NabKaygeAe0NCIWY9ypfjsd7AC/hdVD6HRATcUzBEJhU/5NZmuJTX1glE1."
  ## Intellij Role
   intellij_edition: ultimate
   intellij_version: '2019.1.1'
   intellij_mirror: 'http://download.jetbrains.com/idea'
   intellij_install_dir: /opt/idea/idea-{{ intellij_edition }}-{{ intellij_version }}
   intellij_plugin_manager_url: 'https://plugins.jetbrains.com/pluginManager/'
   intellij_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/tmp/') }}"
   intellij_default_maven_home: '/usr/share/maven'
   users: 
     - username: danfoulkes
       intellij_jdks:
          - name: '1.8'
            home: /usr/lib/jvm/java-8-openjdk-amd64 
       intellij_idea_download_timeout_seconds: 600
       intellij_default_jdk: '1.8'

  become_method: sudo    