---
  - name: tooling from apt
    apt: 
       name: 
            - openconnect
            - htop
            - jq
    become: true
 
  - name: install keychain application
    apt:
      name:
       - keychain
    become: true    

  - name: install base packages
    apt:
      name:
         - python3.10-dev
         - python3.10
         - build-essential
      state: present
      update_cache: yes
      cache_valid_time: 604800
    become: true

  - name: change user shell to fish
    user:
       name: "{{ system_user }}"
       shell: /bin/fish
    become: true   


  # issues with this module atm , we consider reintroduction when more stable.
  #
  # - name: install snapd
  #   apt:
  #     name:
  #         - snapd
  #   become: yes

  # - name: install simplenote an easy to-use note taking application
  #   snap:
  #      name:
  #          - simplenote
  #   become_user: "{{ system_user }}"
  #   become: yes
